# Generated by Django 4.1.3 on 2022-12-04 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
